version: '3.8'
services:
  srv:
    image: ducheved/gitsrv
    hostname: api-cc.imeow.pro
    ports:
      - 41002:41002
    environment:
      - ADDRESS=0.0.0.0
      - PORT=41002
      - UNIT=1
      - TYPE=1
      - PROTOCOL=http
    restart: on-failure

  frnt:
    image: ducheved/gitfrnt
    hostname: frnt
    ports:
      - 41003:80
    restart: on-failure