version: '3.8'
services:
  srv:
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        - SRVNAME=${SRV_HOSTNAME}
    hostname: ${SRV_HOSTNAME}
    ports:
      - "${SRV_PORT}:${SRV_PORT}"
    environment:
      - ADDRESS=0.0.0.0
      - PORT=${SRV_PORT}
      - UNIT=1
      - TYPE=1
    restart: on-failure

  frnt:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_APP_API_URL=${PROTOCOL}://${SRV_HOSTNAME}${SRV_PORT_HOSTNAME}
    hostname: frnt
    ports:
      - ${FRNT_PORT}:80
    restart: on-failure