name: Publish Docker images
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push srv image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        tags: username/srv:latest
        build-args: 
          SRVNAME: ${{ secrets.SRV_HOSTNAME }}
    - name: Build and push frnt image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: username/frnt:latest
        build-args: 
          VITE_APP_API_URL: ${{ secrets.PROTOCOL }}://${{ secrets.SRV_HOSTNAME }}${{ secrets.SRV_PORT_HOSTNAME }}